import type { SiteSettingKey } from './siteSettings';

type Field={key:SiteSettingKey;label:string;type?:'toggle'|'number'|'textarea';hint?:string};
export const ADMIN_CONTROL_GROUPS:{title:string;description:string;fields:Field[]}[]=[
 {title:'Homepage manager',description:'Control the main welcome message and the amount of featured content.',fields:[{key:'homepage_badge',label:'Trust badge'},{key:'homepage_heading_line_1',label:'Heading line 1'},{key:'homepage_heading_line_2',label:'Heading line 2'},{key:'homepage_intro',label:'Introduction',type:'textarea'},{key:'homepage_featured_cars',label:'Featured cars shown',type:'number'},{key:'homepage_featured_drivers',label:'Featured drivers shown',type:'number'}]},
 {title:'Member & upload limits',description:'Default operational limits. Individual owner car allowances can still be managed from Members.',fields:[{key:'max_vehicles_per_owner',label:'Default cars per owner',type:'number'},{key:'connection_limit_daily',label:'Connection requests per day',type:'number'},{key:'upload_limit_mb',label:'Maximum upload size (MB)',type:'number'}]},
 {title:'Feature controls',description:'Switch major member-facing capabilities on or off.',fields:[{key:'registration_enabled',label:'New registrations',type:'toggle'},{key:'google_signin_enabled',label:'Google sign-in',type:'toggle'},{key:'new_listings_enabled',label:'New vehicle listings',type:'toggle'},{key:'chat_images_enabled',label:'Images in chats',type:'toggle'},{key:'maintenance_mode',label:'Maintenance mode',type:'toggle'},{key:'maintenance_message',label:'Maintenance message',type:'textarea'}]},
 {title:'Notification delivery',description:'Choose which important events are also delivered by email.',fields:[{key:'connection_email_enabled',label:'Connection emails',type:'toggle'},{key:'message_email_enabled',label:'New-message emails',type:'toggle'},{key:'welcome_email_enabled',label:'Welcome emails',type:'toggle'},{key:'expiry_email_enabled',label:'Expiry-reminder emails',type:'toggle'}]},
 {title:'Email templates',description:'Set reusable subject lines for transactional messages.',fields:[{key:'email_welcome_subject',label:'Welcome subject'},{key:'email_connection_subject',label:'Connection subject'},{key:'email_message_subject',label:'New-message subject'},{key:'email_expiry_subject',label:'Expiry reminder subject'}]},
 {title:'Moderation rules',description:'Control document scanning and the response to expired records.',fields:[{key:'expiry_warning_days',label:'Reminder days',hint:'Comma separated, e.g. 30,7,1,0'},{key:'auto_hide_expired_listings',label:'Automatically hide affected listings',type:'toggle'}]},
 {title:'Account requirements',description:'Define the information expected from new members.',fields:[{key:'require_email',label:'Email required',type:'toggle'},{key:'required_phone',label:'Phone required',type:'toggle'},{key:'required_location',label:'Residential area required',type:'toggle'},{key:'required_languages',label:'Languages required',type:'toggle'}]},
 {title:'Support management',description:'Publish support availability, hours, and the acknowledgement message.',fields:[{key:'support_available',label:'Support available',type:'toggle'},{key:'support_hours',label:'Support hours'},{key:'support_auto_reply',label:'Automatic acknowledgement',type:'textarea'}]},
 {title:'Search & sharing (SEO)',description:'Manage the homepage search title, summary, and topic phrases.',fields:[{key:'seo_home_title',label:'Homepage search title'},{key:'seo_home_description',label:'Homepage search description',type:'textarea'},{key:'seo_keywords',label:'Related search topics'}]},
 {title:'Retention policy',description:'Policy periods only; changing these values never silently deletes records.',fields:[{key:'analytics_retention_days',label:'Analytics days',type:'number'},{key:'notification_retention_days',label:'Notification days',type:'number'},{key:'chat_retention_days',label:'Chat days',type:'number'}]},
];
export const ADMIN_CONTROL_SETTING_KEYS = ADMIN_CONTROL_GROUPS.flatMap(group => group.fields.map(field => field.key));
