import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import { PGlite } from '@electric-sql/pglite';

test('member reviews, private feedback, permissions and recurring prompt cooldowns', async () => {
  const db = new PGlite();
  try {
    await db.exec(`
      CREATE ROLE anon; CREATE ROLE authenticated; CREATE SCHEMA auth;
      CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('test.uid',true),'')::uuid $$;
      GRANT USAGE ON SCHEMA auth TO anon,authenticated;
      CREATE TABLE profiles(id uuid PRIMARY KEY,role text,is_suspended boolean DEFAULT false,created_at timestamptz DEFAULT now()-interval '40 days',rating numeric DEFAULT 5,rating_count int DEFAULT 0,contracts_completed int DEFAULT 0);
      CREATE FUNCTION is_admin() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER AS $$ SELECT EXISTS(SELECT 1 FROM profiles WHERE id=auth.uid() AND role='admin') $$;
      CREATE TABLE connections(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),requester_id uuid,recipient_id uuid,status text);
      CREATE TABLE applications(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),driver_id uuid,owner_id uuid,status text);
      CREATE TABLE conversations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),driver_id uuid,owner_id uuid,admin_id uuid,connection_id uuid,application_id uuid);
      CREATE TABLE messages(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),conversation_id uuid,type text);
      CREATE TABLE reviews(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),application_id uuid NOT NULL,reviewer_id uuid,reviewee_id uuid,rating int NOT NULL CHECK(rating BETWEEN 1 AND 5),content text,created_at timestamptz DEFAULT now(),UNIQUE(application_id,reviewer_id));
      CREATE TABLE reports(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),reported_id uuid,status text);
      CREATE TABLE notifications(user_id uuid,type text,title text,body text,data jsonb);
      GRANT SELECT ON ALL TABLES IN SCHEMA public TO authenticated;
    `);
    // Execute the actual existing rating and application-review functions.
    const previous = await readFile(new URL('../supabase/migrations/20260826233000_ratings_and_vehicle_platforms.sql', import.meta.url),'utf8');
    await db.exec(previous.slice(0, previous.indexOf('ALTER TABLE public.vehicles')));
    await db.exec(await readFile(new URL('../supabase/migrations/20260909120000_member_reviews_and_experience_feedback.sql', import.meta.url),'utf8'));
    await db.exec(await readFile(new URL('../supabase/migrations/20260911180000_one_review_per_member.sql', import.meta.url),'utf8'));
    const owner=randomUUID(), driver=randomUUID(), other=randomUUID(), admin=randomUUID(), newbie=randomUUID();
    await db.query("INSERT INTO profiles(id,role) VALUES($1,'owner'),($2,'driver'),($3,'driver'),($4,'admin'),($5,'owner')",[owner,driver,other,admin,newbie]);
    await db.query('UPDATE profiles SET created_at=now() WHERE id=$1',[newbie]);
    const chat=randomUUID(), conn=randomUUID(), support=randomUUID(), app=randomUUID(), oldChat=randomUUID();
    await db.query("INSERT INTO connections VALUES($1,$2,$3,'accepted')",[conn,driver,owner]);
    await db.query('INSERT INTO conversations(id,driver_id,owner_id,connection_id) VALUES($1,$2,$3,$4)',[chat,driver,owner,conn]);
    await db.query('INSERT INTO conversations(id,driver_id,admin_id) VALUES($1,$2,$3)',[support,driver,admin]);
    await db.query("INSERT INTO applications VALUES($1,$2,$3,'completed')",[app,other,owner]);
    await db.query('INSERT INTO conversations(id,driver_id,owner_id,application_id) VALUES($1,$2,$3,$4)',[oldChat,other,owner,app]);
    const asUser = async (id, role='authenticated') => { await db.exec('RESET ROLE'); await db.query("SELECT set_config('test.uid',$1,false)",[id]); await db.exec(`SET ROLE ${role}`); };
    const scalar = async (sql,args=[]) => (await db.query(sql,args)).rows[0].value;
    const review = (conversation,rating,comment='Great communication') => scalar('SELECT to_jsonb(submit_conversation_review($1,$2,$3)) AS value',[conversation,rating,comment]);
    const claim = (kind='site',conversation=null) => scalar('SELECT claim_experience_prompt($1,$2) AS value',[kind,conversation]);
    const feedback = (kind='site',rating=5,id=randomUUID(),conversation=null,comment='Easy to use') => scalar('SELECT submit_experience_feedback($1,$2,$3,$4,$5) AS value',[kind,rating,comment,id,conversation]);
    await asUser(other);
    await assert.rejects(review(chat,5),/Only the two connected members/);
    const negative = await review(oldChat,1,'Needs better communication');
    assert.equal(negative.rating,1);
    assert.equal((await review(oldChat,5)).id,negative.id,'old application review cannot be counted twice');
    await asUser(driver);
    const positive = await review(chat,5);
    assert.equal(positive.rating,5);
    assert.equal(Number(await scalar('SELECT rating AS value FROM profiles WHERE id=$1',[owner])),3,'positive review increases average from 1 to 3');
    assert.equal(await scalar('SELECT rating_count AS value FROM profiles WHERE id=$1',[owner]),2);
    assert.equal((await review(chat,1)).id,positive.id,'retry does not create or replace a review');
    await asUser(driver, 'postgres');
    const repeatConnection = randomUUID(), repeatChat = randomUUID(), repeatApp = randomUUID(), repeatAppChat = randomUUID();
    await db.query("INSERT INTO connections VALUES($1,$2,$3,'accepted')", [repeatConnection, driver, owner]);
    await db.query('INSERT INTO conversations(id,driver_id,owner_id,connection_id) VALUES($1,$2,$3,$4)', [repeatChat, driver, owner, repeatConnection]);
    await db.query("INSERT INTO applications VALUES($1,$2,$3,'completed')", [repeatApp, driver, owner]);
    await db.query('INSERT INTO conversations(id,driver_id,owner_id,application_id) VALUES($1,$2,$3,$4)', [repeatAppChat, driver, owner, repeatApp]);
    await assert.rejects(db.query('INSERT INTO reviews(connection_id,reviewer_id,reviewee_id,rating) VALUES($1,$2,$3,1)', [repeatConnection,driver,owner]), /reviews_one_per_member_pair/);
    await asUser(driver);
    assert.equal((await review(repeatChat,1)).id,positive.id,'a new connection cannot create a second rating for the same member');
    assert.equal((await review(repeatAppChat,1)).id,positive.id,'application chats reuse the member rating too');
    await assert.rejects(db.query('SELECT submit_review($1,1,NULL)',[repeatApp]), /reviews_one_per_member_pair/);
    assert.equal(await scalar('SELECT count(*)::int AS value FROM reviews WHERE reviewer_id=$1 AND reviewee_id=$2',[driver,owner]),1);
    assert.equal(await scalar('SELECT count(*)::int AS value FROM notifications WHERE user_id=$1 AND type=\'review\'',[owner]),1,'retries do not create extra review notifications');
    assert.equal(await scalar('SELECT rating_count AS value FROM profiles WHERE id=$1',[owner]),2,'repeat chats do not increase rating count');
    await assert.rejects(review(chat,null),/Choose 1 to 5/);
    await assert.rejects(review(chat,6),/Choose 1 to 5/);
    await assert.rejects(review(chat,5,'x'.repeat(2001)),/2000/);
    await assert.rejects(review(support,5),/connected members/);
    await asUser(admin);
    await assert.rejects(review(chat,5),/active member/);
    await asUser(owner,'postgres');
    await db.query("UPDATE connections SET status='pending' WHERE id=$1",[conn]);
    await asUser(owner);
    await assert.rejects(review(chat,4),/accepted connection/);
    await asUser(owner,'postgres');
    await db.query("UPDATE connections SET status='ended' WHERE id=$1",[conn]);
    await db.query("INSERT INTO reports(reported_id,status) VALUES($1,'resolved')",[owner]);
    assert.equal(Number(await scalar('SELECT rating AS value FROM profiles WHERE id=$1',[owner])),2.9,'report penalty is preserved');
    await asUser(owner);
    assert.equal((await review(chat,4)).rating,4,'ended connection can be reviewed by the other participant');
    await assert.rejects(db.query('INSERT INTO reviews(connection_id,reviewer_id,reviewee_id,rating) VALUES($1,$2,$3,5)',[conn,owner,driver]),/permission denied/);

    await asUser(newbie);
    assert.equal(await claim(),false,'new accounts are not immediately prompted');
    await asUser(driver);
    assert.equal(await claim('chat',chat),false,'empty chat is not prompted');
    await asUser(driver,'postgres');
    await db.query("INSERT INTO messages(conversation_id,type) VALUES($1,'text'),($1,'text')",[chat]);
    await asUser(driver);
    assert.equal(await claim('chat',chat),true);
    assert.equal(await claim('chat',chat),false,'cross-tab claim cannot repeat');
    assert.equal(await claim(),false,'site and chat prompts do not stack in the same day');
    await asUser(driver,'postgres');
    await db.query("UPDATE experience_prompt_state SET prompted_at=now()-interval '2 days' WHERE user_id=$1",[driver]);
    await asUser(driver);
    assert.equal(await claim('chat',chat),false,'weekly cooldown survives navigation and logout');
    assert.equal(await claim(),true,'site prompt becomes independently eligible');
    await asUser(driver,'postgres');
    await db.query("UPDATE experience_prompt_state SET prompted_at=now()-interval '31 days',next_prompt_at=now()-interval '1 day' WHERE user_id=$1",[driver]);
    await asUser(driver);
    assert.equal(await claim('chat',chat),true,'prompt recurs after cooldown');

    const request=randomUUID(), entry=await feedback('site',5,request,null,'Love the site');
    assert.equal(await feedback('site',5,request),entry,'submission retries are idempotent');
    await assert.rejects(feedback(),/wait a few minutes/);
    await assert.rejects(feedback('site',0),/Choose 1 to 5/);
    await assert.rejects(feedback('site',null),/Choose 1 to 5/);
    await assert.rejects(feedback('site',5,randomUUID(),null,'x'.repeat(2001)),/2000/);
    await assert.rejects(feedback('unknown'),/Choose chat or site/);
    await assert.rejects(feedback('site',5,randomUUID(),chat),/not linked/);
    const chatFeedback=await feedback('chat',2,randomUUID(),support,'Please make replies faster');
    assert.ok(chatFeedback,'members can privately rate support messaging');
    assert.equal(await scalar('SELECT count(*)::int AS value FROM experience_feedback'),2);
    await assert.rejects(db.query("INSERT INTO experience_feedback(user_id,kind,rating,request_id) VALUES($1,'site',5,$2)",[driver,randomUUID()]),/permission denied/);
    await assert.rejects(db.query('UPDATE experience_feedback SET reviewed_at=now()'),/permission denied/);
    await assert.rejects(db.query('SELECT admin_mark_feedback_reviewed($1)',[entry]),/Administrator/);
    await asUser(other);
    assert.equal(await scalar('SELECT count(*)::int AS value FROM experience_feedback'),0,'another member cannot read private comments');
    await assert.rejects(feedback('chat',5,randomUUID(),chat),/only rate your own/);
    await asUser(admin);
    assert.equal(await scalar('SELECT count(*)::int AS value FROM experience_feedback'),2);
    await db.query('SELECT admin_mark_feedback_reviewed($1)',[entry]);
    assert.equal(await scalar('SELECT reviewed_at IS NOT NULL AS value FROM experience_feedback WHERE id=$1',[entry]),true);
    await asUser(driver,'postgres');
    await db.query('UPDATE profiles SET is_suspended=true WHERE id=$1',[driver]);
    await asUser(driver);
    await assert.rejects(feedback(),/active member/);
    await assert.rejects(claim(),/active member/);
    await asUser('', 'anon');
    await assert.rejects(feedback(),/permission denied/);
    await assert.rejects(review(chat,5),/permission denied/);
    await assert.rejects(db.query('SELECT * FROM experience_feedback'),/permission denied/);
    await db.exec('RESET ROLE');
    await db.exec(await readFile(new URL('../supabase/migrations/20260909140000_feedback_popup_and_support_continuity.sql', import.meta.url),'utf8'));
    await asUser(newbie);
    assert.equal(await claim(),true,'new members can see the real site popup after browsing');
    assert.equal(await claim(),false,'refresh does not immediately repeat a popup');
    await asUser(owner);
    assert.equal(await claim('chat',chat),true);
    assert.equal(await claim(),true,'first site popup is not starved by a chat rating invitation');
    await feedback('site',5);
    await asUser(owner,'postgres');
    await db.query("UPDATE experience_prompt_state SET prompted_at=now()-interval '2 days' WHERE user_id=$1",[owner]);
    await asUser(owner);
    assert.equal(await claim(),false,'a completed site rating keeps its monthly cooldown');
  } finally { await db.close(); }
});
