import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { distanceKm, withinLocationRadius } from '../src/lib/locationRadius.ts';

test('location radius recognizes nearby and distant Kenyan areas',()=>{
  assert.ok((distanceKm('Westlands','Kilimani')||99)<10);
  assert.equal(withinLocationRadius('Kilimani','Westlands',10),true);
  assert.equal(withinLocationRadius('Mombasa','Westlands',50),false);
  assert.equal(withinLocationRadius('Unknown estate','Unknown',10),true);
});
test('installable site has manifest and safe navigation fallback',()=>{
  const manifest=JSON.parse(readFileSync('public/manifest.webmanifest','utf8'));
  assert.equal(manifest.display,'standalone');assert.equal(manifest.name,'11Drive');
  assert.equal(manifest.start_url,'/?source=pwa');assert.equal(manifest.background_color,'#ffffff');
  assert.ok(manifest.icons.some((icon:{src:string;sizes:string})=>icon.src.startsWith('/app-icon-192.png')&&icon.sizes==='192x192'));
  assert.ok(manifest.icons.some((icon:{src:string;sizes:string;purpose:string})=>icon.src.startsWith('/app-icon-512.png')&&icon.sizes==='512x512'&&icon.purpose.includes('maskable')));
  assert.match(readFileSync('public/app-icon.svg','utf8'),/aria-label="11Drive"/);
  const worker=readFileSync('public/sw.js','utf8');assert.match(worker,/request\.mode==='navigate'/);
  assert.match(worker,/11drive-shell-v4/);
  const document=readFileSync('index.html','utf8');
  assert.match(document,/name="theme-color" content="#ffffff"/);
  assert.match(document,/apple-touch-icon[^>]+app-icon-192\.png\?v=4/);
  const intro=readFileSync('src/components/LaunchIntro.tsx','utf8');assert.match(intro,/Opening \$\{siteName\}/);assert.doesNotMatch(intro,/launch-caret/);
  assert.match(intro,/ElevenDriveWordmark decorative/);
  assert.match(intro,/setTimeout\(onComplete, 5400\)/);
  const styles=readFileSync('src/index.css','utf8');
  assert.match(styles,/launch-slide-away/);
  assert.match(styles,/launch-logo-enter/);
  assert.match(styles,/launch-wheel-turn/);
  assert.match(styles,/launch-loading-progress/);
  assert.match(styles,/translateY\(-100%\)/);
  assert.doesNotMatch(styles,/launch-fade/);
  assert.match(intro,/backgroundType === 'video' && allowVideo/);
  assert.match(intro,/objectPosition: backgroundPosition/);
  const app=readFileSync('src/App.tsx','utf8');
  assert.match(app,/11drive-launch-intro-seen/);
  assert.match(app,/display-mode: standalone/);
  assert.match(app,/get\('source'\) === 'pwa'/);
  assert.match(app,/!showLaunchIntro && <span aria-hidden="true"/);
  assert.match(app,/settings\.launch_intro_enabled === 'true'/);
  assert.match(app,/settings\.launch_intro_background_enabled === 'true'/);
  const admin=readFileSync('src/pages/AdminPage.tsx','utf8');
  assert.match(admin,/Animated 11Drive launch/);
  assert.match(admin,/Background during launch/);
  const installPrompt=readFileSync('src/components/InstallAppPrompt.tsx','utf8');
  assert.match(installPrompt,/2 \* 24 \* 60 \* 60 \* 1000/);
  assert.match(installPrompt,/beforeinstallprompt/);
  assert.match(readFileSync('src/components/Layout.tsx','utf8'),/<InstallAppPrompt/);
});
test('member tools include profile, report, connection, and calendar states',()=>{
  const checklist=readFileSync('src/components/ProfileCompletionChecklist.tsx','utf8');
  assert.match(checklist,/Complete your profile/);
  assert.match(checklist,/profile-health#about-you/);
  assert.match(checklist,/profile-health#platform-history/);
  assert.match(checklist,/!photoComplete\|\|!aboutComplete\?'\/settings\?from=profile-health#profile-details'/);
  assert.match(checklist,/Next: add \{nextStep\}/);
  const onboarding=readFileSync('src/pages/DriverOnboardingPage.tsx','utf8');
  assert.match(onboarding,/Save profile details/);
  assert.match(onboarding,/update your profile health immediately/);
  assert.match(onboarding,/fromProfileHealth.*navigate\('\/dashboard'/s);
  assert.match(readFileSync('src/pages/SettingsPage.tsx','utf8'),/fromProfileHealth.*navigate\('\/dashboard'/s);
  assert.match(readFileSync('src/components/ReportFollowUpTracker.tsx','utf8'),/Under review/);
  assert.match(readFileSync('src/components/ConnectionProgress.tsx','utf8'),/Awaiting reply/);
  assert.match(readFileSync('src/components/AvailabilityCalendar.tsx','utf8'),/Weekly availability/);
  assert.match(readFileSync('src/components/AvailabilityCalendar.tsx','utf8'),/Show on profile/);
  assert.match(readFileSync('src/components/WeeklyAvailabilityView.tsx','utf8'),/!enabled\|\|!slots\.length/);
  const migration=readFileSync('supabase/migrations/20260909006000_member_experience_tools.sql','utf8');
  assert.match(migration,/UNIQUE\(user_id, day_of_week\)/);assert.match(migration,/user_id=auth\.uid\(\)/);
});
test('admin theme choices expose their real colour codes',()=>{
  const admin=readFileSync('src/pages/AdminPage.tsx','utf8');
  const themes=readFileSync('src/lib/siteTheme.ts','utf8');
  assert.match(admin,/Every swatch shows its exact HEX code/);
  assert.match(admin,/\{colour\}/);
  assert.match(admin,/Base.*Action.*Surface/s);
  assert.match(themes,/#13d0ff/);
  for(const colour of ['#172554','#2563eb','#4f46e5','#064e3b','#10b981','#134e4a','#14b8a6','#431407','#f97316','#450a0a','#e11d48','#2e1065','#7c3aed','#164e63','#06b6d4']) assert.match(themes,new RegExp(colour));
  for(const theme of ['midnight-cyan','navy-gold','charcoal-coral','forest-amber','plum-rose','slate-teal']) assert.match(themes,new RegExp(theme));
  for(const colour of ['#4a4a4a','#cbcbcb','#ffffe3','#6d8196','#ffc067','#66f4ff','#66c4ff','#7d99aa']) assert.match(themes,new RegExp(colour));
  for(const theme of ['stone-mist','sunlit-sky']) assert.match(themes,new RegExp(theme));
});
test('admin controls the top header name animation',()=>{
  const header=readFileSync('src/components/Header.tsx','utf8');
  const wordmark=readFileSync('src/components/ElevenDriveWordmark.tsx','utf8');
  const admin=readFileSync('src/pages/AdminPage.tsx','utf8');
  const styles=readFileSync('src/index.css','utf8');
  assert.match(header,/header_name_animation/);
  assert.match(header,/header_name_colours/);
  assert.match(admin,/Top header name animation/);
  assert.match(admin,/Top header name colours/);
  assert.match(admin,/11 dark · Drive theme/);
  assert.match(admin,/value="off"/);
  assert.match(wordmark,/site-wordmark-eleven/);
  assert.match(wordmark,/site-wordmark-drive/);
  assert.doesNotMatch(admin,/Colour sweep/);
  assert.match(styles,/site-wordmark--pulse/);
  assert.match(styles,/site-wordmark--float/);
});

test('dark dashboard navigation uses neutral buttons instead of green',()=>{
  const navigation=readFileSync('src/components/DashboardNavigation.tsx','utf8');
  const baseStyles=readFileSync('src/index.css','utf8');
  const palette=readFileSync('src/styles/site-palette.css','utf8');
  assert.match(navigation,/dark:bg-\[#17171a\]/);
  assert.doesNotMatch(navigation,/dark:bg-emerald-950/);
  assert.match(baseStyles,/--ink-50: 36 38 44/);
  assert.match(baseStyles,/dark:bg-\[#17191f\]/);
  assert.match(palette,/A lifted dark palette/);
  assert.match(palette,/\.dark \.card/);
  assert.match(palette,/dark:bg-\[#1d1d20\]/);
});
test('suspensions are atomic and queue reasoned email notifications',()=>{
  const migration=readFileSync('supabase/migrations/20260909008000_suspension_email_notification.sql','utf8');
  const admin=readFileSync('src/pages/AdminPage.tsx','utf8');
  assert.match(admin,/rpc\('admin_suspend_member'/);
  assert.match(migration,/Reason: '\|\|reason/);
  assert.match(migration,/NEW\.type IN \('connection_accepted','message','suspension'\)/);
  assert.match(migration,/event_email_html\(heading,email_message/);
});
test('reinstated members refresh immediately without signing out',()=>{
  const auth=readFileSync('src/lib/auth.tsx','utf8');
  const page=readFileSync('src/pages/SuspendedPage.tsx','utf8');
  assert.match(auth,/is_suspended: next\.is_suspended/);
  assert.match(page,/if \(profile && !profile\.is_suspended\) navigate\('\/dashboard'/);
  assert.match(page,/Check access again/);
});
test('admin reinstatement supports an optional message and both delivery channels',()=>{
  const migration=readFileSync('supabase/migrations/20260909009000_reinstatement_email_notification.sql','utf8');
  const admin=readFileSync('src/pages/AdminPage.tsx','utf8');
  assert.match(admin,/Message <span[^>]*>\(optional\)/);
  assert.match(admin,/rpc\('admin_reinstate_member'/);
  assert.match(migration,/Message from support:/);
  assert.match(migration,/NEW\.type IN \('admin_announcement','reinstatement'\)/);
  assert.match(migration,/event_email_html\(NEW\.title,NEW\.body/);
});
test('footer contact details remain readable over a full-page background',()=>{
  const footer=readFileSync('src/components/Footer.tsx','utf8');
  assert.match(footer,/relative z-10/);
  assert.match(footer,/mailto:\$\{settings\.admin_contact_email\}/);
  assert.match(footer,/bg-ink-50\/90/);
});
test('assistant answers from only the signed-in account summary',()=>{
  const context=readFileSync('src/lib/assistantAccountContext.ts','utf8');
  const assistant=readFileSync('src/components/SiteAssistant.tsx','utf8');
  assert.match(context,/\.eq\('owner_id',userId\)/);
  assert.match(context,/do not inspect private message contents/);
  assert.match(context,/Suggested next steps/);
  assert.match(assistant,/loadAssistantAccountContext\(user\.id,profile\)/);
});
