import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import { PGlite } from '@electric-sql/pglite';

test('report removal is admin-only, audited, idempotent and restores only the correct rating deduction', async () => {
  const db = new PGlite();
  const admin=randomUUID(), member=randomUUID(), reporter=randomUUID();
  const file = name => readFile(new URL('../supabase/migrations/'+name,import.meta.url),'utf8');
  const scalar = async (sql,args=[]) => (await db.query(sql,args)).rows[0].value;
  const asUser = async (id,role='authenticated') => { await db.exec('RESET ROLE'); await db.query("SELECT set_config('test.uid',$1,false)",[id]); await db.exec('SET ROLE '+role); };
  try {
    await db.exec(`
      CREATE ROLE anon; CREATE ROLE authenticated; CREATE SCHEMA auth;
      CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('test.uid',true),'')::uuid $$;
      GRANT USAGE ON SCHEMA auth TO anon,authenticated;
      CREATE TABLE profiles(id uuid PRIMARY KEY,role text,email text,rating numeric DEFAULT 5,rating_count integer DEFAULT 0,contracts_completed integer DEFAULT 0,is_suspended boolean DEFAULT false);
      CREATE FUNCTION is_admin() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER AS $$ SELECT EXISTS(SELECT 1 FROM profiles WHERE id=auth.uid() AND role='admin' AND NOT is_suspended) $$;
      CREATE TABLE applications(id uuid PRIMARY KEY,driver_id uuid,owner_id uuid,status text);
      CREATE TABLE reviews(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),application_id uuid,reviewer_id uuid,reviewee_id uuid,rating integer,content text);
      CREATE TABLE reports(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),reporter_id uuid,reported_id uuid,reason text,description text,target_type text,target_id uuid,status text,created_at timestamptz DEFAULT now());
      CREATE TABLE notifications(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid,type text,title text,body text,data jsonb);
      GRANT SELECT ON profiles,reports,notifications TO authenticated;
      GRANT UPDATE ON reports TO authenticated;
      ALTER TABLE reports ENABLE ROW LEVEL SECURITY;
      CREATE POLICY reports_read ON reports FOR SELECT TO authenticated USING(reporter_id=auth.uid() OR is_admin());
      CREATE POLICY reports_update ON reports FOR UPDATE TO authenticated USING(is_admin()) WITH CHECK(is_admin());
    `);
    const warnings = await file('20260826223000_report_case_management.sql');
    await db.exec(warnings.slice(0,warnings.indexOf('CREATE OR REPLACE FUNCTION')));
    await db.exec('GRANT SELECT ON user_warnings TO authenticated');
    const ratings = await file('20260826233000_ratings_and_vehicle_platforms.sql');
    await db.exec(ratings.slice(0,ratings.indexOf('ALTER TABLE public.vehicles')));
    await db.exec(await file('20260909200000_report_overturn_and_warning_revocation.sql'));
    await db.query("INSERT INTO profiles(id,role) VALUES($1,'admin'),($2,'driver'),($3,'owner')",[admin,member,reporter]);
    const reports = Array.from({length:10},()=>randomUUID());
    for (const id of reports) await db.query("INSERT INTO reports(id,reporter_id,reported_id,reason,description,target_type,status) VALUES($1,$2,$3,'Missed appointment','Disputed appointment','user','resolved')",[id,reporter,member]);
    const rating = () => scalar('SELECT rating AS value FROM profiles WHERE id=$1',[member]).then(Number);
    const overturn = (id=reports[0],reason='Appointment was cancelled by the other member.') => scalar('SELECT admin_overturn_report($1,$2) AS value',[id,reason]);
    const warn = id => scalar("SELECT admin_issue_report_warning($1,'Please keep agreed appointments') AS value",[id]);
    const standing = () => scalar('SELECT my_account_standing() AS value');
    assert.equal(await rating(),4);
    await asUser('', 'anon'); await assert.rejects(overturn(),/permission denied/);
    await asUser(member); await assert.rejects(overturn(),/Administrator access/);
    assert.equal((await standing()).reports.length,10);
    await asUser(admin); await assert.rejects(overturn(reports[0],'short'),/10–2000/);
    await assert.rejects(overturn(randomUUID()),/not found/);
    assert.equal(await warn(reports[0]),1); assert.equal(await warn(reports[0]),1);
    assert.equal(Number(await scalar('SELECT count(*) AS value FROM user_warnings')),1,'warning retries cannot duplicate');
    const result = await overturn();
    assert.equal(Number(result.rating_before),4); assert.equal(Number(result.rating_after),4.1);
    assert.equal(result.warnings_revoked,1); assert.equal(await rating(),4.1);
    assert.equal(await scalar('SELECT revoked_at IS NOT NULL AS value FROM user_warnings WHERE report_id=$1',[reports[0]]),true);
    assert.equal(await scalar('SELECT dismissed_by AS value FROM reports WHERE id=$1',[reports[0]]),admin);
    assert.equal(Number(await scalar('SELECT count(*) AS value FROM reports')),10,'the original case is not deleted');
    const notifications = Number(await scalar('SELECT count(*) AS value FROM notifications'));
    assert.equal((await overturn()).already_removed,true);
    assert.equal(Number(await scalar('SELECT count(*) AS value FROM notifications')),notifications,'retry must not notify twice');
    await assert.rejects(warn(reports[0]),/dismissed report/);
    await assert.rejects(db.query("UPDATE reports SET status='resolved' WHERE id=$1",[reports[0]]),/cannot be reopened/);
    assert.equal(await warn(reports[1]),1,'revoked warning is excluded from future warning counts');
    await asUser(member);
    const mine=await standing(); assert.equal(mine.reports.length,9); assert.equal(mine.warnings.length,1); assert.equal(mine.removed_reports.length,1);
    assert.ok(!JSON.stringify(mine).includes(reporter),'private standing does not disclose reporter identity');
    assert.equal(Number(await scalar('SELECT count(*) AS value FROM reports')),0,'reported member gets only the caller-scoped explanation, not full cases');
    await asUser(reporter); assert.equal((await standing()).reports.length,0); assert.equal((await standing()).warnings.length,0);
    await asUser(admin,'postgres');
    await db.query('INSERT INTO reviews(reviewee_id,rating) VALUES($1,1),($1,5)',[member]);
    await db.query('SELECT recalculate_profile_rating($1)',[member]);
    await asUser(admin);
    assert.equal(await rating(),2.1);
    await overturn(reports[1]); assert.equal(await rating(),2.2,'real review average is preserved, never reset to 5');
    const open=randomUUID();
    await asUser(admin,'postgres'); await db.query("INSERT INTO reports(id,reporter_id,reported_id,reason,target_type,status) VALUES($1,$2,$3,'Question','user','open')",[open,reporter,member]);
    await asUser(admin); await overturn(open); assert.equal(await rating(),2.2,'an open report had no deduction to restore');
    await asUser(admin,'postgres');
    for(let i=0;i<30;i++) await db.query("INSERT INTO reports(reporter_id,reported_id,reason,target_type,status) VALUES($1,$2,'Another report','user','resolved')",[reporter,member]);
    await asUser(admin); assert.equal(await rating(),1); await overturn(reports[2]); assert.equal(await rating(),1,'minimum rating and remaining deductions are respected');
  } finally {await db.close();}
});
