import { useEffect,useState } from 'react';
import { AlertTriangle,Ban,CheckCircle2,RefreshCw,ShieldCheck } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { type SiteSettingKey,useSiteSettings } from '@/lib/siteSettings';
import { useToast } from './useToast';
const switches:[SiteSettingKey,string,string][]=[['security_risk_alerts','Risk alerts','Record suspicious activity and show it here.'],['security_rate_limits','Rate limits','Pause excessive connection and message activity.'],['security_new_device_alerts','New-device alerts','Notify users and admins when a new browser is detected.'],['security_admin_mfa_required','Require admin two-factor authentication','Only enable after every administrator has enrolled an authenticator.'],['security_auto_restrictions','Automatic temporary restrictions','Allow high-confidence rules to pause risky actions.'],['security_upload_validation','Upload security','Require safe image types and upload-size validation.'],['security_spam_detection','Spam detection','Stop repeated messages and burst activity.'],['security_account_history','Account-change history','Record sensitive email, phone, role, and suspension changes.'],['security_admin_notifications','Admin security notifications','Send in-app alerts to administrators for detected risks.'],['security_blocklist','Block list','Apply active email, phone, and device blocks.'],['security_immutable_audit','Protected audit trail','Keep security evidence unavailable for ordinary editing or deletion.'],['security_data_minimization','Data minimization','Use device hashes and avoid storing raw IP addresses.']];
type EventRow={id:string;user_id:string|null;event_type:string;severity:string;summary:string;status:string;created_at:string};type Block={id:string;kind:string;value:string;reason:string;expires_at:string|null;active:boolean};
export function AdminSecurityCentre(){const{settings,refreshSettings}=useSiteSettings();const{toast}=useToast();const[events,setEvents]=useState<EventRow[]>([]);const[blocks,setBlocks]=useState<Block[]>([]);const[kind,setKind]=useState('email');const[value,setValue]=useState('');const[reason,setReason]=useState('');
 const load=async()=>{const[e,b]=await Promise.all([supabase.from('security_events').select('*').order('created_at',{ascending:false}).limit(100),supabase.from('security_blocks').select('*').eq('active',true).order('created_at',{ascending:false})]);setEvents((e.data as EventRow[])||[]);setBlocks((b.data as Block[])||[])};useEffect(()=>{void load()},[]);
 const toggle=async(key:SiteSettingKey,on:boolean)=>{if(key==='security_admin_mfa_required'&&on){const{data}=await supabase.auth.mfa.getAuthenticatorAssuranceLevel();if(data?.currentLevel!=='aal2')return toast('Enroll and verify two-factor authentication on this admin account first.','error')}const{error}=await supabase.from('site_settings').upsert({key,value:String(on),updated_at:new Date().toISOString()},{onConflict:'key'});if(error)return toast(error.message,'error');await refreshSettings();toast(`${on?'Enabled':'Disabled'} ${switches.find(item=>item[0]===key)?.[1]}.`)};
 const review=async(id:string,status:'reviewed'|'resolved')=>{const{error}=await supabase.rpc('admin_review_security_event',{p_id:id,p_status:status});if(error)return toast(error.message,'error');await load()};
 const addBlock=async()=>{if(!value.trim()||reason.trim().length<3)return toast('Enter a value and reason.','error');const{error}=await supabase.from('security_blocks').insert({kind,value:value.trim().toLowerCase(),reason:reason.trim()});if(error)return toast(error.message,'error');setValue('');setReason('');await load();toast('Security block added.')};
 const disableBlock=async(id:string)=>{const{error}=await supabase.from('security_blocks').update({active:false}).eq('id',id);if(error)return toast(error.message,'error');await load()};
 return <div className="space-y-5"><section className="card p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="flex items-center gap-2 text-xl font-bold text-ink-900"><ShieldCheck className="h-5 w-5"/>Security Centre</h2><p className="mt-1 text-sm text-ink-500">Detection, prevention, alerts, and review controls. No raw IP addresses are stored.</p></div><button className="btn-secondary" onClick={()=>void load()}><RefreshCw className="h-4 w-4"/>Refresh</button></div><div className="mt-5 grid gap-3 lg:grid-cols-2">{switches.map(([key,label,help])=><label key={key} className="flex items-start justify-between gap-4 rounded-xl border border-ink-200 p-4"><span><span className="block text-sm font-semibold text-ink-900">{label}</span><span className="mt-1 block text-xs leading-5 text-ink-500">{help}</span></span><input type="checkbox" className="mt-1 h-5 w-5 shrink-0 accent-orange-600" checked={settings[key]==='true'} onChange={event=>void toggle(key,event.target.checked)}/></label>)}</div><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="label">Connections per hour<input type="number" min="1" className="input mt-1" value={settings.security_connection_hourly_limit} onChange={async e=>{await supabase.from('site_settings').upsert({key:'security_connection_hourly_limit',value:e.target.value,updated_at:new Date().toISOString()},{onConflict:'key'});await refreshSettings()}}/></label><label className="label">Messages per minute<input type="number" min="1" className="input mt-1" value={settings.security_message_minute_limit} onChange={async e=>{await supabase.from('site_settings').upsert({key:'security_message_minute_limit',value:e.target.value,updated_at:new Date().toISOString()},{onConflict:'key'});await refreshSettings()}}/></label></div></section>
 <section className="card p-5"><h3 className="font-bold text-ink-900">Active block list</h3><div className="mt-3 grid gap-2 sm:grid-cols-[140px_1fr_1fr_auto]"><select className="input" value={kind} onChange={e=>setKind(e.target.value)}><option value="email">Email</option><option value="phone">Phone</option><option value="device">Device hash</option></select><input className="input" value={value} onChange={e=>setValue(e.target.value)} placeholder="Value to block"/><input className="input" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Reason"/><button className="btn-primary" onClick={()=>void addBlock()}><Ban className="h-4 w-4"/>Block</button></div><div className="mt-4 space-y-2">{blocks.map(block=><div key={block.id} className="flex flex-wrap items-center gap-2 rounded-xl bg-ink-50 p-3 text-sm"><span className="badge-danger uppercase">{block.kind}</span><span className="min-w-0 flex-1 break-all">{block.value} — {block.reason}</span><button className="btn-ghost text-xs" onClick={()=>void disableBlock(block.id)}>Remove block</button></div>)}{!blocks.length&&<p className="text-sm text-ink-500">No active blocks.</p>}</div></section>
 <section className="card p-5"><h3 className="font-bold text-ink-900">Risk alerts</h3><div className="mt-3 space-y-2">{events.map(event=><div key={event.id} className="rounded-xl border border-ink-200 p-4"><div className="flex flex-wrap items-center gap-2"><AlertTriangle className={`h-4 w-4 ${event.severity==='critical'||event.severity==='high'?'text-danger':'text-warning'}`}/><span className="font-semibold text-ink-900">{event.summary}</span><span className="badge-neutral uppercase">{event.severity}</span><span className="ml-auto text-xs text-ink-400">{new Date(event.created_at).toLocaleString()}</span></div><p className="mt-1 text-xs text-ink-500">{event.event_type.replace(/_/g,' ')} · Account {event.user_id||'unknown'} · {event.status}</p>{event.status==='open'&&<div className="mt-3 flex gap-2"><button className="btn-secondary px-3 py-1.5 text-xs" onClick={()=>void review(event.id,'reviewed')}>Mark reviewed</button><button className="btn-primary px-3 py-1.5 text-xs" onClick={()=>void review(event.id,'resolved')}><CheckCircle2 className="h-3.5 w-3.5"/>Resolve</button></div>}</div>)}{!events.length&&<p className="text-sm text-ink-500">No suspicious activity detected.</p>}</div></section></div>}
