import { useState } from 'react';
import { Loader2, UserPlus } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { isValidEmail, isValidPhone, normalizePhone } from '@/lib/phoneAuth';
import { hasFirstAndSecondName, parseLanguages } from '@/lib/profileValidation';
import { isBroadNairobi, SPECIFIC_LOCATION_MESSAGE } from '@/lib/specificLocation';
import { Modal } from './Modal';
import { useToast } from './useToast';

export function AdminAddMember({ onClose,onCreated }:{ onClose:()=>void; onCreated:()=>Promise<void> }) {
 const { toast }=useToast(); const [form,setForm]=useState({name:'',email:'',phone:'',password:'',role:'driver',location:'',languages:'English, Swahili'}); const [accepted,setAccepted]=useState(false); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
 const field=(key:keyof typeof form)=>(event:React.ChangeEvent<HTMLInputElement|HTMLSelectElement>)=>setForm(current=>({...current,[key]:event.target.value}));
 const submit=async(event:React.FormEvent)=>{event.preventDefault();setError('');const languages=parseLanguages(form.languages);if(!hasFirstAndSecondName(form.name))return setError('Enter the member’s first and second name.');if(!isValidEmail(form.email))return setError('Enter a valid email address.');if(!isValidPhone(form.phone))return setError('Enter a valid Kenyan phone number, e.g. 0712 345 678.');if(isBroadNairobi(form.location))return setError(SPECIFIC_LOCATION_MESSAGE);if(languages.length<2)return setError('Add at least two languages.');if(!accepted)return setError('Confirm that the member accepted the current Terms of Service.');setSaving(true);const{error:failure}=await supabase.rpc('admin_create_member',{p_email:form.email,p_password:form.password,p_full_name:form.name,p_phone:normalizePhone(form.phone),p_role:form.role,p_location:form.location,p_languages:languages,p_terms_accepted:accepted});setSaving(false);if(failure)return setError(failure.message);toast('Member added. Their email remains unconfirmed until you verify it from the Members list.');await onCreated();onClose();};
 return <Modal title="Add member" size="lg" onClose={onClose}><form onSubmit={submit} className="space-y-4"><p className="text-sm text-ink-600">Create a driver or car-owner account. Give the temporary password to the member securely, then confirm their email only after verifying ownership.</p>{error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-danger">{error}</p>}<div><label className="label">Full name</label><input className="input" value={form.name} onChange={field('name')} required /></div><div className="grid gap-4 sm:grid-cols-2"><div><label className="label">Email</label><input className="input" type="email" value={form.email} onChange={field('email')} required /></div><div><label className="label">Phone</label><input className="input" type="tel" placeholder="0712 345 678" value={form.phone} onChange={field('phone')} required /></div></div><div className="grid gap-4 sm:grid-cols-2"><div><label className="label">Member type</label><select className="input" value={form.role} onChange={field('role')}><option value="driver">Driver</option><option value="owner">Car owner</option></select></div><div><label className="label">Temporary password</label><input className="input" type="password" minLength={10} value={form.password} onChange={field('password')} placeholder="10+ characters" required /></div></div><div><label className="label">Residential area</label><input className="input" value={form.location} onChange={field('location')} placeholder="e.g. Ongata Rongai" required /></div><div><label className="label">Languages</label><input className="input" value={form.languages} onChange={field('languages')} required /><p className="mt-1 text-xs text-ink-500">At least two, separated by commas.</p></div><label className="flex items-start gap-3 rounded-xl border border-ink-200 p-3 text-sm leading-6"><input type="checkbox" checked={accepted} onChange={event=>setAccepted(event.target.checked)} className="mt-1 h-5 w-5"/><span>I confirm this member accepted the current Terms of Service and authorised me to create this account.</span></label><div className="flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={onClose} disabled={saving}>Cancel</button><button className="btn-primary" disabled={saving}>{saving?<Loader2 className="h-4 w-4 animate-spin"/>:<UserPlus className="h-4 w-4"/>}{saving?'Adding…':'Add member'}</button></div></form></Modal>;
}
