import { useEffect,useState } from 'react';
import { Download,History,Save,Settings2 } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { type SiteSettingKey,type SiteSettings,useSiteSettings } from '@/lib/siteSettings';
import { useToast } from './useToast';

type Field={key:SiteSettingKey;label:string;type?:'toggle'|'number'|'textarea';hint?:string};
const groups:{title:string;description:string;fields:Field[]}[]=[
 {title:'Homepage manager',description:'Control the main welcome message and the amount of featured content.',fields:[{key:'homepage_badge',label:'Trust badge'},{key:'homepage_heading_line_1',label:'Heading line 1'},{key:'homepage_heading_line_2',label:'Heading line 2'},{key:'homepage_intro',label:'Introduction',type:'textarea'},{key:'homepage_featured_cars',label:'Featured cars shown',type:'number'},{key:'homepage_featured_drivers',label:'Featured drivers shown',type:'number'}]},
 {title:'Member & upload limits',description:'Default operational limits. Individual owner car allowances can still be managed from Members.',fields:[{key:'max_vehicles_per_owner',label:'Default cars per owner',type:'number'},{key:'connection_limit_daily',label:'Connection requests per day',type:'number'},{key:'upload_limit_mb',label:'Maximum upload size (MB)',type:'number'}]},
 {title:'Feature controls',description:'Switch major member-facing capabilities on or off.',fields:[{key:'registration_enabled',label:'New registrations',type:'toggle'},{key:'google_signin_enabled',label:'Google sign-in',type:'toggle'},{key:'new_listings_enabled',label:'New vehicle listings',type:'toggle'},{key:'chat_images_enabled',label:'Images in chats',type:'toggle'},{key:'maintenance_mode',label:'Maintenance mode',type:'toggle'},{key:'maintenance_message',label:'Maintenance message',type:'textarea'}]},
 {title:'Notification delivery',description:'Choose which important events are also delivered by email.',fields:[{key:'connection_email_enabled',label:'Connection emails',type:'toggle'},{key:'message_email_enabled',label:'New-message emails',type:'toggle'},{key:'welcome_email_enabled',label:'Welcome emails',type:'toggle'},{key:'expiry_email_enabled',label:'Expiry-reminder emails',type:'toggle'}]},
 {title:'Email templates',description:'Set reusable subject lines for transactional messages.',fields:[{key:'email_welcome_subject',label:'Welcome subject'},{key:'email_connection_subject',label:'Connection subject'},{key:'email_message_subject',label:'New-message subject'},{key:'email_expiry_subject',label:'Expiry reminder subject'}]},
 {title:'Moderation rules',description:'Control document scanning and the response to expired records.',fields:[{key:'expiry_warning_days',label:'Reminder days',hint:'Comma separated, e.g. 30,7,1,0'},{key:'auto_hide_expired_listings',label:'Automatically hide affected listings',type:'toggle'}]},
 {title:'Account requirements',description:'Define the information expected from new members.',fields:[{key:'require_email',label:'Email required',type:'toggle'},{key:'required_phone',label:'Phone required',type:'toggle'},{key:'required_location',label:'Residential area required',type:'toggle'},{key:'required_languages',label:'Languages required',type:'toggle'}]},
 {title:'Support management',description:'Publish support availability, hours, and the acknowledgement message.',fields:[{key:'support_available',label:'Support available',type:'toggle'},{key:'support_hours',label:'Support hours'},{key:'support_auto_reply',label:'Automatic acknowledgement',type:'textarea'}]},
 {title:'Search & sharing (SEO)',description:'Manage the homepage search title, summary, and topic phrases.',fields:[{key:'seo_home_title',label:'Homepage search title'},{key:'seo_home_description',label:'Homepage search description',type:'textarea'},{key:'seo_keywords',label:'Related search topics'}]},
 {title:'Retention policy',description:'Policy periods only; changing these values never silently deletes records.',fields:[{key:'analytics_retention_days',label:'Analytics days',type:'number'},{key:'notification_retention_days',label:'Notification days',type:'number'},{key:'chat_retention_days',label:'Chat days',type:'number'}]},
];
type Audit={id:number;key:string;old_value:string|null;new_value:string|null;changed_at:string;admin_id:string};
export function AdminControlCentre(){const{settings:live,refreshSettings}=useSiteSettings();const{toast}=useToast();const[draft,setDraft]=useState<SiteSettings>(live);const[saving,setSaving]=useState(false);const[audit,setAudit]=useState<Audit[]>([]);useEffect(()=>setDraft(live),[live]);
 const loadAudit=async()=>{const{data}=await supabase.from('admin_settings_audit').select('*').order('changed_at',{ascending:false}).limit(50);setAudit((data as Audit[])||[])};useEffect(()=>{void loadAudit()},[]);
 const save=async()=>{setSaving(true);const changed=Object.entries(draft).filter(([key,value])=>live[key as SiteSettingKey]!==value);const{error}=await supabase.from('site_settings').upsert(changed.map(([key,value])=>({key,value,updated_at:new Date().toISOString()})),{onConflict:'key'});setSaving(false);if(error)return toast(error.message,'error');await refreshSettings();await loadAudit();toast(`${changed.length} control${changed.length===1?'':'s'} saved.`)};
 const csv=(rows:Record<string,unknown>[])=>{if(!rows.length)return '';const keys=Object.keys(rows[0]);const cell=(v:unknown)=>`"${String(v??'').replace(/"/g,'""')}"`;return [keys.map(cell).join(','),...rows.map(row=>keys.map(key=>cell(row[key])).join(','))].join('\n')};
 const exportData=async(kind:'members'|'vehicles'|'reports')=>{const query=kind==='members'?supabase.rpc('admin_list_members'):supabase.from(kind).select('*');const{data,error}=await query;if(error)return toast(error.message,'error');const content=csv((data as Record<string,unknown>[])||[]);const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([content],{type:'text/csv'}));link.download=`11drive-${kind}-${new Date().toISOString().slice(0,10)}.csv`;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000)};
 return <div className="space-y-5"><div className="card p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="flex items-center gap-2 text-xl font-bold text-ink-900"><Settings2 className="h-5 w-5"/>Admin control centre</h2><p className="mt-1 text-sm text-ink-500">Platform content, operations, communication, safety, and data controls.</p></div><button className="btn-primary" disabled={saving} onClick={save}><Save className="h-4 w-4"/>{saving?'Saving…':'Save all changes'}</button></div></div>
  <div className="grid gap-4 xl:grid-cols-2">{groups.map(group=><section key={group.title} className="card p-5"><h3 className="font-bold text-ink-900">{group.title}</h3><p className="mt-1 text-xs leading-5 text-ink-500">{group.description}</p><div className="mt-4 space-y-3">{group.fields.map(field=><div key={field.key}>{field.type==='toggle'?<label className="flex items-center justify-between gap-4 rounded-xl border border-ink-200 p-3 text-sm font-medium text-ink-800"><span>{field.label}</span><input type="checkbox" className="h-5 w-5 accent-orange-600" checked={draft[field.key]==='true'} onChange={event=>setDraft(current=>({...current,[field.key]:String(event.target.checked)}))}/></label>:<><label className="label" htmlFor={`control-${field.key}`}>{field.label}</label>{field.type==='textarea'?<textarea id={`control-${field.key}`} className="input min-h-24" value={draft[field.key]} onChange={event=>setDraft(current=>({...current,[field.key]:event.target.value}))}/>:<input id={`control-${field.key}`} type={field.type==='number'?'number':'text'} min={field.type==='number'?0:undefined} className="input" value={draft[field.key]} onChange={event=>setDraft(current=>({...current,[field.key]:event.target.value}))}/>} {field.hint&&<p className="mt-1 text-xs text-ink-400">{field.hint}</p>}</>}</div>)}</div></section>)}</div>
  <section className="card p-5"><h3 className="font-bold text-ink-900">Featured content</h3><p className="mt-1 text-sm text-ink-500">Choose individual featured vehicles from the Cars admin area. The homepage limits above control how many are shown. Approved drivers continue to be ranked by promotion and trust status.</p></section>
  <section className="card p-5"><h3 className="font-bold text-ink-900">Data exports</h3><p className="mt-1 text-sm text-ink-500">Download a current CSV for offline review.</p><div className="mt-3 flex flex-wrap gap-2">{(['members','vehicles','reports'] as const).map(kind=><button key={kind} className="btn-secondary capitalize" onClick={()=>void exportData(kind)}><Download className="h-4 w-4"/>{kind}</button>)}</div></section>
  <section className="card p-5"><h3 className="flex items-center gap-2 font-bold text-ink-900"><History className="h-4 w-4"/>Admin settings activity</h3><div className="mt-3 divide-y divide-ink-100">{audit.map(item=><div key={item.id} className="py-3 text-sm"><p className="font-medium text-ink-800">{item.key.replace(/_/g,' ')}</p><p className="break-words text-xs text-ink-500">{item.old_value||'empty'} → {item.new_value||'empty'} · {new Date(item.changed_at).toLocaleString()}</p></div>)}{!audit.length&&<p className="text-sm text-ink-500">No recorded setting changes yet.</p>}</div></section>
 </div>}
