INSERT INTO public.site_settings(key,value) VALUES
('security_risk_alerts','true'),('security_rate_limits','true'),('security_new_device_alerts','true'),('security_admin_mfa_required','false'),('security_auto_restrictions','false'),('security_upload_validation','true'),('security_spam_detection','true'),('security_account_history','true'),('security_admin_notifications','true'),('security_blocklist','true'),('security_immutable_audit','true'),('security_data_minimization','true'),('security_connection_hourly_limit','20'),('security_message_minute_limit','30') ON CONFLICT(key) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.security_events(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid,event_type text NOT NULL,severity text NOT NULL CHECK(severity IN('low','medium','high','critical')),summary text NOT NULL,details jsonb NOT NULL DEFAULT '{}'::jsonb,status text NOT NULL DEFAULT 'open' CHECK(status IN('open','reviewed','resolved')),created_at timestamptz NOT NULL DEFAULT now(),reviewed_by uuid,reviewed_at timestamptz);
CREATE INDEX IF NOT EXISTS security_events_status_created_idx ON public.security_events(status,created_at DESC);
ALTER TABLE public.security_events ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS security_events_admin_read ON public.security_events;
CREATE POLICY security_events_admin_read ON public.security_events FOR SELECT TO authenticated USING(public.is_admin());
GRANT SELECT ON public.security_events TO authenticated;
REVOKE INSERT,UPDATE,DELETE ON public.security_events FROM anon,authenticated;

CREATE TABLE IF NOT EXISTS public.security_devices(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,device_hash text NOT NULL,label text NOT NULL DEFAULT 'Browser',first_seen_at timestamptz NOT NULL DEFAULT now(),last_seen_at timestamptz NOT NULL DEFAULT now(),trusted boolean NOT NULL DEFAULT false,UNIQUE(user_id,device_hash));
ALTER TABLE public.security_devices ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS security_devices_own_or_admin ON public.security_devices;
CREATE POLICY security_devices_own_or_admin ON public.security_devices FOR SELECT TO authenticated USING(user_id=auth.uid() OR public.is_admin());
GRANT SELECT ON public.security_devices TO authenticated;

CREATE TABLE IF NOT EXISTS public.security_blocks(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),kind text NOT NULL CHECK(kind IN('email','phone','device')),value text NOT NULL,reason text NOT NULL,expires_at timestamptz,created_by uuid NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),active boolean NOT NULL DEFAULT true);
ALTER TABLE public.security_blocks ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS security_blocks_admin_all ON public.security_blocks;
CREATE POLICY security_blocks_admin_all ON public.security_blocks FOR ALL TO authenticated USING(public.is_admin()) WITH CHECK(public.is_admin());
GRANT SELECT,INSERT,UPDATE ON public.security_blocks TO authenticated;
REVOKE DELETE ON public.security_blocks FROM authenticated,anon;

CREATE OR REPLACE FUNCTION public.security_setting_on(p_key text,p_default boolean DEFAULT true) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT coalesce((SELECT value='true' FROM site_settings WHERE key=p_key),p_default) $$;
REVOKE ALL ON FUNCTION public.security_setting_on(text,boolean) FROM PUBLIC,anon,authenticated;

CREATE OR REPLACE FUNCTION public.add_security_event(p_user uuid,p_type text,p_severity text,p_summary text,p_details jsonb DEFAULT '{}'::jsonb) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
BEGIN IF public.security_setting_on('security_risk_alerts',true) THEN INSERT INTO security_events(user_id,event_type,severity,summary,details) VALUES(p_user,p_type,p_severity,p_summary,coalesce(p_details,'{}')); IF public.security_setting_on('security_admin_notifications',true) THEN INSERT INTO notifications(user_id,type,title,body,data) SELECT id,'security_alert','Security alert',p_summary,jsonb_build_object('path','/admin?tab=security','severity',p_severity) FROM profiles WHERE role='admin'; END IF; END IF; END $$;
REVOKE ALL ON FUNCTION public.add_security_event(uuid,text,text,text,jsonb) FROM PUBLIC,anon,authenticated;

CREATE OR REPLACE FUNCTION public.security_activity_guard() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE actor uuid; recent_count integer; same_count integer; hourly_limit integer; minute_limit integer;
BEGIN actor:=CASE WHEN TG_TABLE_NAME='connections' THEN NEW.requester_id ELSE NEW.sender_id END;
 IF public.security_setting_on('security_blocklist',true) AND EXISTS(SELECT 1 FROM security_blocks b JOIN profiles p ON p.id=actor WHERE b.active AND (b.expires_at IS NULL OR b.expires_at>now()) AND ((b.kind='email' AND lower(b.value)=lower(p.email)) OR (b.kind='phone' AND b.value=p.phone))) THEN RAISE EXCEPTION 'This account action is temporarily restricted. Contact support.'; END IF;
 IF TG_TABLE_NAME='connections' THEN SELECT count(*) INTO recent_count FROM connections WHERE requester_id=actor AND created_at>now()-interval '1 hour'; hourly_limit:=coalesce((SELECT value::int FROM site_settings WHERE key='security_connection_hourly_limit'),20); IF recent_count>=greatest(hourly_limit,1) THEN PERFORM add_security_event(actor,'connection_rate','high','Unusually rapid connection requests',jsonb_build_object('count',recent_count)); IF public.security_setting_on('security_rate_limits',true) THEN RAISE EXCEPTION 'Connection request limit reached. Please wait and try again.'; END IF; END IF;
 ELSE SELECT count(*) INTO recent_count FROM messages WHERE sender_id=actor AND created_at>now()-interval '1 minute'; minute_limit:=coalesce((SELECT value::int FROM site_settings WHERE key='security_message_minute_limit'),30); SELECT count(*) INTO same_count FROM messages WHERE sender_id=actor AND created_at>now()-interval '10 minutes' AND body=NEW.body AND length(coalesce(NEW.body,''))>0; IF same_count>=4 AND public.security_setting_on('security_spam_detection',true) THEN PERFORM add_security_event(actor,'message_spam','high','Repeated message content detected',jsonb_build_object('duplicates',same_count)); RAISE EXCEPTION 'Repeated messages were paused. Please wait before trying again.'; END IF; IF recent_count>=greatest(minute_limit,1) THEN PERFORM add_security_event(actor,'message_rate','high','Unusually rapid messaging detected',jsonb_build_object('count',recent_count)); IF public.security_setting_on('security_rate_limits',true) THEN RAISE EXCEPTION 'Message limit reached. Please wait and try again.'; END IF; END IF; END IF; RETURN NEW; END $$;
DROP TRIGGER IF EXISTS trg_security_connection_guard ON public.connections;
CREATE TRIGGER trg_security_connection_guard BEFORE INSERT ON public.connections FOR EACH ROW EXECUTE FUNCTION public.security_activity_guard();
DROP TRIGGER IF EXISTS trg_security_message_guard ON public.messages;
CREATE TRIGGER trg_security_message_guard BEFORE INSERT ON public.messages FOR EACH ROW EXECUTE FUNCTION public.security_activity_guard();

CREATE OR REPLACE FUNCTION public.security_profile_history() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN IF public.security_setting_on('security_account_history',true) AND (OLD.email,OLD.phone,OLD.role,OLD.is_suspended) IS DISTINCT FROM (NEW.email,NEW.phone,NEW.role,NEW.is_suspended) THEN PERFORM add_security_event(NEW.id,'account_change',CASE WHEN OLD.role IS DISTINCT FROM NEW.role OR OLD.is_suspended IS DISTINCT FROM NEW.is_suspended THEN 'high' ELSE 'medium' END,'Sensitive account details changed',jsonb_build_object('email_changed',OLD.email IS DISTINCT FROM NEW.email,'phone_changed',OLD.phone IS DISTINCT FROM NEW.phone,'role_changed',OLD.role IS DISTINCT FROM NEW.role,'suspension_changed',OLD.is_suspended IS DISTINCT FROM NEW.is_suspended)); END IF; RETURN NEW; END $$;
DROP TRIGGER IF EXISTS trg_security_profile_history ON public.profiles;
CREATE TRIGGER trg_security_profile_history AFTER UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.security_profile_history();

CREATE OR REPLACE FUNCTION public.security_upload_monitor() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE actor uuid; recent_count integer; BEGIN actor:=CASE WHEN TG_TABLE_NAME='documents' THEN NEW.user_id ELSE (SELECT owner_id FROM vehicles WHERE id=NEW.vehicle_id) END; IF actor IS NULL OR NOT public.security_setting_on('security_upload_validation',true) THEN RETURN NEW; END IF; IF TG_TABLE_NAME='documents' THEN SELECT count(*) INTO recent_count FROM documents WHERE user_id=actor AND created_at>now()-interval '1 hour'; ELSE SELECT count(*) INTO recent_count FROM vehicle_photos vp JOIN vehicles v ON v.id=vp.vehicle_id WHERE v.owner_id=actor AND vp.created_at>now()-interval '1 hour'; END IF; IF recent_count>=20 THEN PERFORM add_security_event(actor,'upload_burst','high','Unusually frequent uploads detected',jsonb_build_object('count',recent_count,'area',TG_TABLE_NAME)); IF public.security_setting_on('security_auto_restrictions',false) THEN RAISE EXCEPTION 'Uploads are temporarily paused because of unusual activity. Try again later.'; END IF; END IF; RETURN NEW; END $$;
DROP TRIGGER IF EXISTS trg_security_document_upload ON public.documents;
CREATE TRIGGER trg_security_document_upload BEFORE INSERT ON public.documents FOR EACH ROW EXECUTE FUNCTION public.security_upload_monitor();
DROP TRIGGER IF EXISTS trg_security_vehicle_photo_upload ON public.vehicle_photos;
CREATE TRIGGER trg_security_vehicle_photo_upload BEFORE INSERT ON public.vehicle_photos FOR EACH ROW EXECUTE FUNCTION public.security_upload_monitor();

CREATE OR REPLACE FUNCTION public.register_security_device(p_hash text,p_label text DEFAULT 'Browser') RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE is_new boolean:=false; BEGIN IF auth.uid() IS NULL OR length(p_hash)<16 THEN RAISE EXCEPTION 'Invalid device registration'; END IF; IF public.security_setting_on('security_blocklist',true) AND EXISTS(SELECT 1 FROM security_blocks WHERE active AND kind='device' AND value=p_hash AND (expires_at IS NULL OR expires_at>now())) THEN RAISE EXCEPTION 'This device is restricted. Contact support.'; END IF; INSERT INTO security_devices(user_id,device_hash,label) VALUES(auth.uid(),p_hash,left(coalesce(nullif(trim(p_label),''),'Browser'),80)) ON CONFLICT(user_id,device_hash) DO UPDATE SET last_seen_at=now() RETURNING (xmax=0) INTO is_new; IF is_new AND public.security_setting_on('security_new_device_alerts',true) THEN INSERT INTO notifications(user_id,type,title,body,data) VALUES(auth.uid(),'security_device','New device sign-in','Your account was opened on a browser we have not seen before. If this was not you, change your password and contact support.',jsonb_build_object('path','/settings')); PERFORM add_security_event(auth.uid(),'new_device','medium','New browser detected for a member',jsonb_build_object('label',left(p_label,80))); END IF; RETURN is_new; END $$;
GRANT EXECUTE ON FUNCTION public.register_security_device(text,text) TO authenticated;
CREATE OR REPLACE FUNCTION public.admin_review_security_event(p_id uuid,p_status text) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN IF NOT public.is_admin() THEN RAISE EXCEPTION 'Admin access required'; END IF; IF p_status NOT IN('reviewed','resolved') THEN RAISE EXCEPTION 'Invalid status'; END IF; UPDATE security_events SET status=p_status,reviewed_by=auth.uid(),reviewed_at=now() WHERE id=p_id; END $$;
GRANT EXECUTE ON FUNCTION public.admin_review_security_event(uuid,text) TO authenticated;
NOTIFY pgrst,'reload schema';
